modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="mcplantator"
version="1.0.0"
displayName="MCPlantator"
authors="Jikai"
description='''
MCPlantator adds a botanical workbench and new plantable crops to Minecraft.
Grow your own gunpowder with the Gunpowder Plant!
'''

[[dependencies.mcplantator]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcplantator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
